
[platformio]
default_envs = esp32dev

[env:upesy_wroom]
platform = espressif32
board = upesy_wroom
framework = arduino
monitor_speed = 115200
lib_deps=h2zero/NimBLE-Arduino@^2.1.0
build_src_filter =
	+<*>
	-<BLE_come.cpp>

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
lib_deps=h2zero/NimBLE-Arduino@^2.1.0
build_src_filter =
	+<*>
	-<BLE_come.cpp>